[package]
name = "rand-wallet"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rand-wallet"
path = "src/main.rs"


[dependencies]
otc-models = { workspace = true }
argon2 = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
rand = { version = "0.9", features = ["std_rng"] }
snafu = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
blockchain-utils = { workspace = true }
bitcoin = { workspace = true }
clap = { workspace = true }
alloy = { workspace = true }
hex = { workspace = true }
