global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - mm-prometheus:9090
  - job_name: node-exporter
    static_configs:
      - targets:
          - mm-node-exporter:9100
  - job_name: market-maker
    static_configs:
      - targets:
          - market-maker:9000

